### ISSUE TITLE
Typo Disclaimer in English

### ISSUE THREAD

**Issue by sdellachiesa** [GiulioGenova/ODBZ#7]
**WRONG** 
Meteorologial data downloaded form this app comes with no warranty and has not been validated by the data provider nor by the authors of the app. This app is intended only to facilitate retrieving data from the Meteorologial Open Data Suedtirol API. The dataset avaiable refers to the last three years.

**CORRECTED -  PLEASE DOUBLE CHECK IT**
Meteorological data downloaded from this app comes with no warranty and has not been validated by the data provider nor by the authors of the app. This app is intended only to facilitate retrieving data from the Meteorological Open Data Suedtirol API. The dataset available refers to the last three years.

**Comment by yakopuz** [comment]
The dataset available refers to the last three years.
Meglio forse
The available dataset covers the last three years.

**Comment by GiulioGenova** [comment]
Thank you for pointing that out. I added both suggestions in the commit: 04b69bc1ed5b0537e5f9bd88bda3a5270e36d045
